name: Go-Lint

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.22
    - name: Checkout
      uses: actions/checkout@v4
    - name: Run the golangci-lint
      uses: golangci/golangci-lint-action@v4
      with:
        version:  latest
        args: --timeout=5m
    - name: Go Tidy
      run: |
        trap 'echo "::error file=go.mod,title=Go Tidy Check::Commit would leave go.mod untidy"' ERR
        go clean -cache -modcache
        go mod tidy
        git diff --exit-code